### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by OmgImAlexis** [labdiscord/statcord.js#58]
If `await this.post()` throws it won't be caught which would result in an unhandled promise rejection being thrown.
https://github.com/labdiscord/statcord.js/blob/1f1926426c437ea1944ffbc9252d71062ac61fe7/src/Statcord.js#L222-L227

For example adding this to the start of `post()` will cause it to throw only **AFTER** the first time simulating in thesetInterval block.

```
if (this.pleaseThrow) throw new Error('failed!');
else this.pleaseThrow = true;
```

```
(node:31857) UnhandledPromiseRejectionWarning: Error: failed!
    at Statcord.post (/Users/xo/code/AutoModBot/AutoMod/node_modules/statcord.js/src/Statcord.js:73:30)
    at Timeout._onTimeout (/Users/xo/code/AutoModBot/AutoMod/node_modules/statcord.js/src/Statcord.js:226:28)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31857) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:31857) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Solixity** [comment]
Closed as stale. If this is still a problem, please open a new issue.

**Comment by OmgImAlexis** [comment]
This is still a problem.
